#!/bin/bash

echo Updating\ and\ Installing\ Dependencies

sudo apt-get update
sudo apt-get install libudev-dev libcurl4-openssl-dev

echo Configuring\ And\ Installing\ cgminer

cd cgminer
./autogen.sh
./configure --enable-dualminer --enable-scrypt --disable-opencl  --prefix=/home/pi/DualMiner-cgminer/cgminer
make && make install

tput setaf 6; echo Done!
