#!/bin/bash
echo "Save As"
read varsave
echo \

echo "Pool URL"
read varlink
echo \

echo "Pool Worker"
read varworker
echo \

echo "Worker Password"
read varpass
echo \

> $varsave

echo "#!/bin/bash" >> $varsave
echo "cd cgminer" >> $varsave
echo "sudo ./cgminer --scrypt -o $varURL -u $varWorker -p $varPass –T" >> $varsave

chmod +x $varsave
